// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSO0cRfolM_V4pZzV392KxkefhSHyXlFU',
    appId: '1:540842635851:web:af6db7f5ac7f40543213ce',
    messagingSenderId: '540842635851',
    projectId: 'favourite-places-9af22',
    authDomain: 'favourite-places-9af22.firebaseapp.com',
    storageBucket: 'favourite-places-9af22.firebasestorage.app',
    measurementId: 'G-4WMNF5DKE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALaZ9rSGHMIhCJdcQ4Y2a7kb9Bafgxkkw',
    appId: '1:540842635851:android:e03f040827b685bf3213ce',
    messagingSenderId: '540842635851',
    projectId: 'favourite-places-9af22',
    storageBucket: 'favourite-places-9af22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1XO7f_nw8sIfHj7qYeILjpCr3riKXw0',
    appId: '1:540842635851:ios:5e473d9ca3bc0af73213ce',
    messagingSenderId: '540842635851',
    projectId: 'favourite-places-9af22',
    storageBucket: 'favourite-places-9af22.firebasestorage.app',
    iosClientId: '540842635851-k0o3r6c417rq3go678l6gjbe8lijrfgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.favouritePlaces',
  );
}
